/*/// <reference types="cypress" />

//This is a test suite
describe('test suite', function(){
    //This is a test case (not included in assignment, only used for login purpose and practice)
    
    it('Perform valid login', function(){
        cy.visit('http://localhost:3000')
        cy.title().should('include', 'Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.wait(300)
        cy.get('.user > .btn').click()
        cy.contains('Login')

    })

    it('Enter page Rooms', function(){
        cy.visit('http://localhost:3000')
        cy.title().should('include', 'Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.wait(300)
        cy.get(':nth-child(1) > .btn').click()
        cy.contains('Rooms')
        cy.get(':nth-child(3) > .btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.user > .btn').click()
        cy.contains('Login') 
         
    })

    it('Delete client', function(){
        cy.visit('http://localhost:3000')
        cy.title().should('include', 'Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.wait(500)
        cy.get('.blocks > :nth-child(2) > .btn').click()
        cy.contains('Clients')
        cy.wait(500)
        cy.get(':nth-child(2) > .action').click()
        cy.get('.menu')
        cy.contains('Edit')
        cy.get('.menu > :nth-child(2)').contains('Delete').click()
        cy.get('.clients > :nth-child(2)').should('not.exist')
        cy.get('.user > .btn').click()
        cy.contains('Login')
        
    })
    
    it('Add client', function(){
        cy.visit('http://localhost:3000')
        cy.title().should('include', 'Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.wait(500)
        cy.get('.blocks > :nth-child(2) > .btn').click()
        cy.contains('Clients')
        cy.get('h2 > .btn').click()
        cy.contains('New Client')
        cy.get(':nth-child(1) > input').type('Mikael Eriksson')
        cy.get(':nth-child(2) > input').type('mikael.eriksson@example.com')
        cy.get(':nth-child(3) > input').type('070 000 0002')
        cy.get('.blue').click()
        cy.get('.user > .btn').click()
        cy.contains('Login')
        
    })

    it('Mark bill as paid', function(){
        cy.visit('http://localhost:3000')
        cy.title().should('include', 'Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.wait(300)
        cy.get('.blocks > :nth-child(3) > .btn').click()
        cy.contains('Bills')
        cy.wait(300)
        cy.get('.action').click()
        cy.get('.menu > :nth-child(1)').click()
        cy.contains('Bill:')
        cy.wait(300)
        cy.get('.checkbox').click()
        cy.get('.blue').click()
        cy.contains('Paid: Yes')
        cy.get('.action').click()
        cy.get('.menu > :nth-child(1)').click()
        cy.contains('Bill:')
        cy.wait(300)
        cy.get('.checkbox').click()
        cy.get('.blue').click()
        cy.contains('Paid: No')
        cy.get('.user > .btn').click()
        cy.contains('Login')
        
    })

    it('Delete client', function(){
        cy.visit('http://localhost:3000')
        cy.title().should('include', 'Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.wait(500)
        cy.get('.blocks > :nth-child(1) > .btn').click()
        cy.contains('Rooms')
        cy.wait(500)
        cy.get(':nth-child(1) > .action').click()
        cy.get('.menu')
        cy.contains('Edit').click()
        cy.contains('Room:')
        cy.wait(500)
        //cy.get(':nth-child(3) > input').type('Single')
        //cy.get('.menu > :nth-child(2)').contains('Delete').click
        //cy.get('.clients > :nth-child(2)').should('not.exist')
        //cy.get('.user > .btn').click()
        //cy.contains('Login')
        
    })

})*/